---
- hosts: database
  roles:
    - mysql

- hosts: wordpress
  roles:
    - webserver
    - wordpress

    # - name: 'Configura Apache para servir o Wordpress'
    ### não mais necessario pois foi criado uma configuração para template
    # - copy:
    #     src: 'files/000-default.conf'
    #     dest: '/etc/apache2/sites-available/000-default.conf'
    #   become: yes
    #   notify:
    #     - restart apache


  # NEW
    # - name: 'Instala pacotes do sistema operacional'
    #   apt:
    #     name:
    #     - php5
    #     - apache2
    #     - libapache2-mod-php5
    #     state: latest
    #   become: yes
  
    # BEFORE
    # tasks:
    #   - name: 'Instalando php5'
    #     apt: 
    #       name: php5
    #       state: latest
    #     become: yes
    #   - name: 'Instalando Apache2'
    #     apt: 
    #       name: apache2
    #       state: latest
    #     become: yes
    #   - name: 'Instalando modephp'
    #     apt:
    #       name: libapache2-mod-php5
    #       state: latest
    #     become: yes